version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: daily
      time: '22:00'
    labels:
      - dependencies
      
  - package-ecosystem: "docker"
    directory: 'ariang/'
    schedule:
      interval: "daily"
      time: '22:00'
    labels:
      - dependencies

  - package-ecosystem: "docker"
    directory: 'darkhttpd/'
    schedule:
      interval: "daily"
      time: '22:00'
    labels:
      - dependencies

  - package-ecosystem: "docker"
    directory: 'frps/'
    schedule:
      interval: "daily"
      time: '22:00'
    labels:
      - dependencies

  - package-ecosystem: "docker"
    directory: 'frpc/'
    schedule:
      interval: "daily"
      time: '22:00'
    labels:
      - dependencies
      
  - package-ecosystem: "docker"
    directory: 'homebox/'
    schedule:
      interval: "daily"
      time: '22:00'
    labels:
      - dependencies
