name: 【Docker】 Push darkhttpd

on:
  push:
    paths: [ "darkhttpd/README.md" ]
  pull_request:
    paths: [ "darkhttpd/README.md" ]
  workflow_dispatch: ~
  
jobs:
  description:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          repository: ${{ secrets.DOCKER_USERNAME }}/darkhttpd
          readme-filepath: darkhttpd/README.md
